trigger: none

pool: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'  # Adjust the version if needed
  displayName: 'Install Node.js'

- checkout: self  # Ensure the repository is correctly checked out

- script: |
    #cd path/to/your/project  # If package.json is in a subfolder
    npm install
    npm run build
  displayName: 'npm install and build'

